services:
  postgres:
    image: postgres:15
    container_name: postgres_dw_elt
    environment:
      POSTGRES_DB: dw_mutuelle_elt
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_elt:/var/lib/postgresql/data
      - ./Data:/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data_elt:
