silver_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: dw_user
      password: dw_password
      port: 5432
      dbname: dw_mutuelle_elt
      schema: silver
